# Generated by Django 5.1.7 on 2025-04-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('caption', models.TextField()),
                ('storage_path', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('likes_count', models.IntegerField()),
                ('dislikes_count', models.IntegerField()),
                ('is_reported', models.BooleanField()),
            ],
            options={
                'db_table': 'images',
                'managed': False,
            },
        ),
    ]
