# Generated by Django 5.1.7 on 2025-04-30 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_userinteractions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInteractions',
        ),
    ]
