# Generated by Django 5.1.7 on 2025-04-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInteractions',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('interaction_type', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_interactions',
                'managed': False,
            },
        ),
    ]
